In [1]:
import json
import pandas as pd

with open('brokerage_data.json', 'r') as f:
    loaded_data = json.load(f)

In [2]:
sections = {
    'Income': [],
    'Transaction': [],
    'Deposit & Withdrawals': [],
    'Fees': []
}

for period, data in loaded_data.items():
    for key in sections:        
        if key in data:
            for record in data[key]:
                record['Statement'] = period 
            sections[key].extend(data[key])

trading_data = {key: pd.DataFrame(val) for key, val in sections.items()}

for df in trading_data.values():
    if 'Trade Date' in df.columns:
        df['Trade Date'] = pd.to_datetime(df['Trade Date'])

In [7]:
trading_data['Transaction']['Entry Type'].unique()

array(['High-Yield Cash Sweep', 'Trade Entry', None, 'Stock Split',
       'ReOrg CA', 'Merger/Acquisition'], dtype=object)

In [29]:
trading_data['Transaction'][trading_data['Transaction']['Entry Type'] == 'ReOrg CA']

,Trade Date,Entry Type,Side,Symbol,Description,Quantity,Price,Amount,Commission,Statement
118,2025-05-27,ReOrg CA,None,219RGT073,Worthless Removal - 219RGT073,-2.816941,NaN,NaN,NaN,2025-May

In [23]:
trading_data['Transaction'][trading_data['Transaction']['Entry Type'] == 'Merger/Acquisition']

,Trade Date,Entry Type,Side,Symbol,Description,Quantity,Price,Amount,Commission,Statement
208,2024-02-23,Merger/Acquisition,None,PAK,Cash Merger $16.9524 per share,-1.0,17.1,NaN,NaN,2024-February

In [24]:
trading_data['Transaction'][trading_data['Transaction']['Entry Type'] == 'Stock Split']

,Trade Date,Entry Type,Side,Symbol,Description,Quantity,Price,Amount,Commission,Statement
79,2024-09-30,Stock Split,None,RYAAY,"REMOVE, From QTY:-0.126237123, To QTY:0.315592...",-0.126237,118.82,NaN,NaN,2024-September
80,2024-09-30,Stock Split,None,RYAAY,"ADD, From QTY:-0.126237123, To QTY:0.315592808...",0.315593,47.53,NaN,NaN,2024-September
156,2024-06-10,Stock Split,None,NVDA,"REMOVE, From QTY:-0.031545224, To QTY:0.315452...",-0.031545,443.81,NaN,NaN,2024-June
157,2024-06-10,Stock Split,None,NVDA,"ADD, From QTY:-0.031545224, To QTY:0.31545224,...",0.315452,44.38,NaN,NaN,2024-June

In [28]:
cumulative_positions = trading_data['Transaction'].groupby('Symbol').sum('Quantity').round(10)
cumulative_positions[cumulative_positions['Quantity'] > 0]

        Quantity    Price  Amount  Commission
Symbol
AMZN    0.149980   295.40  -22.22         0.0
APO     0.273329   125.12  -34.20         1.0
ARM     0.080826   185.58  -15.00         1.0
BRW     4.707718    14.86  -35.00         0.0
CEFS    1.114267    36.02  -20.00         0.0
CLM     2.816941    14.20  -20.00         0.0
GOF     3.000000    26.60  -40.27         0.0
GSBD    2.436461    29.20  -35.00         0.0
IBB     0.047022   126.75   -5.96         0.0
IJR     0.227215   110.03  -25.00         0.0
INDA    0.877661   154.17  -46.33         1.0
IPO     1.288476    83.51  -52.79         2.0
JPMB    1.688699    40.55  -68.47         1.0
KKR     0.378202   282.39  -53.00         2.0
LLY     0.062060   604.25  -37.50         0.0
LUX     2.000000    45.45  -45.45         0.0
META    0.138582   927.13  -42.34         0.0
MOAT    1.399621   923.28 -113.79         5.0
MSFT    0.255834  1812.33  -96.87         1.0
NVDA    0.250397  1625.07   -7.49         2.0
OCSL    1.042269    38.75  -20.36         0.0
RYAAY   0.315593   285.17  -15.00         1.0
SMOT    0.718432    34.80  -25.00         1.0
SPY     0.177676  1310.29  -77.53         0.0
TPVG    4.000000    40.93  -40.93         0.0
USRT    0.167590   100.16   -8.44         0.0
VOO     1.552063  7607.05 -736.81        11.0
VOOG    0.478497  2005.27 -124.29         2.0
VXUS    0.716810    59.99  -43.00         1.0
XLF     1.309464   174.11  -57.26         3.0
XLK     1.223873  1800.20  -96.51         5.0
XLV     0.289189   136.66  -39.52         1.0