In [1]:
import json
import pandas as pd

with open('brokerage_data.json', 'r') as f:
    loaded_data = json.load(f)

In [2]:
sections = {
    'Income': [],
    'Transaction': [],
    'Deposit & Withdrawals': [],
    'Fees': []
}

for period, data in loaded_data.items():
    for key in sections:        
        if key in data:
            for record in data[key]:
                record['Statement'] = period 
            sections[key].extend(data[key])

trading_data = {key: pd.DataFrame(val) for key, val in sections.items()}

for df in trading_data.values():
    if 'Trade Date' in df.columns:
        df['Trade Date'] = pd.to_datetime(df['Trade Date'])

In [7]:
trading_data['Transaction']['Entry Type'].unique()

array(['High-Yield Cash Sweep', 'Trade Entry', None, 'Stock Split',
       'ReOrg CA', 'Merger/Acquisition'], dtype=object)

In [23]:
trading_data['Transaction'][trading_data['Transaction']['Entry Type'] == 'Merger/Acquisition']

,Trade Date,Entry Type,Side,Symbol,Description,Quantity,Price,Amount,Commission,Statement
208,2024-02-23,Merger/Acquisition,None,PAK,Cash Merger $16.9524 per share,-1.0,17.1,NaN,NaN,2024-February

In [17]:
trading_data['Transaction'][trading_data['Transaction']['Entry Type'] == "Trade Entry"].groupby('Symbol').sum('Quantity').round(10)

        Quantity    Price  Amount  Commission
Symbol
ADBE    0.000000  1613.73   -0.67         1.0
AMZN    0.149980   295.40  -22.22         0.0
APO     0.273329   125.12  -34.20         1.0
ARKK    0.000000   106.39    5.19         2.0
ARM     0.080826   185.58  -15.00         1.0
BA      0.000000  1176.51   -0.18         1.0
BKNG    0.000000  9705.58    2.13         1.0
BRW     4.707718    14.86  -35.00         0.0
CAT    -0.000000   878.91    4.06         1.0
CEFS    1.114267    36.02  -20.00         0.0
CLM     2.816941    14.20  -20.00         0.0
COIN   -0.000000   610.61   20.53         1.0
DE      0.000000  1168.95   -2.79         1.0
EL      0.000000   394.88   -5.54         1.0
EWJ     0.000000   135.45    1.41         1.0
GOF     3.000000    26.60  -40.27         0.0
GSBD    2.436461    29.20  -35.00         0.0
IBB     0.047022   126.75   -5.96         0.0
IJR     0.227215   110.03  -25.00         0.0
INDA    0.877661   154.17  -46.33         1.0
IPO     1.288476    83.51  -52.79         2.0
JPMB    1.688699    40.55  -68.47         1.0
KKR     0.378202   282.39  -53.00         2.0
KSA     0.000000    83.86   -0.27         1.0
LLY     0.062060   604.25  -37.50         0.0
LUX     2.000000    45.45  -45.45         0.0
MBB     0.000000   186.46   -0.04         1.0
MCHI    0.000000   121.29    3.99         2.0
META    0.138582   927.13  -42.34         0.0
MOAT    1.399621   923.28 -113.79         5.0
MSFT    0.255834  1812.33  -96.87         1.0
NOBL   -0.000000   383.65    8.65         1.0
NVDA   -0.033510  1136.88   -7.49         2.0
NVO     0.000000   242.25   16.76         1.0
OCSL    1.042269    38.75  -20.36         0.0
PAK     1.000000    17.10  -17.10         0.0
PERI    0.000000    66.88    0.08         0.0
ROM     0.000000   135.58   -6.09         2.0
RYAAY   0.126237   118.82  -15.00         1.0
SHOP    0.000000   184.56    1.51         1.0
SMOT    0.718432    34.80  -25.00         1.0
SPHY   -0.000000    69.03    0.48         1.0
SPSM    0.000000   130.78    1.20         1.0
SPXL    0.000000   151.06    0.62         0.0
SPY     0.177676  1310.29  -77.53         0.0
STIP    0.000000   295.46    0.38         1.0
TPVG    4.000000    40.93  -40.93         0.0
TQQQ    0.000000   199.71   -4.11         2.0
TSLA   -0.000000  1459.27   12.09         1.0
UAE     0.000000   102.41   -2.30         1.0
USRT    0.167590   100.16   -8.44         0.0
VBK     0.000000   508.92    1.87         1.0
VHT     0.000000  1489.68    9.92         1.0
VOO     1.552063  7607.05 -736.81        11.0
VOOG    0.478497  2005.27 -124.29         2.0
VXUS    0.716810    59.99  -43.00         1.0
XLF     1.309464   174.11  -57.26         3.0
XLK     1.223873  1800.20  -96.51         5.0
XLV     0.289189   136.66  -39.52         1.0